"""POST /api/generate-lesson and GET /api/lessons/{lesson_id}/attempts."""

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.crud import cached_lesson, get_attempts_for_lesson, persist_lesson
from app.database import get_db
from app.models import SkillGap
from app.schemas import AttemptHistoryItem, LessonRequest, LessonResponse
from app.services.agents import generate_lesson_agent

router = APIRouter(prefix="/api", tags=["lesson"])


@router.post("/generate-lesson", response_model=LessonResponse)
def create_lesson(payload: LessonRequest, db: Session = Depends(get_db)):
    """Return micro-lesson (cached or freshly generated by agent) and persist to database."""
    skill_name = payload.skill.strip()
    gap_reason = ""

    if payload.skill_gap_id:
        gap = db.get(SkillGap, payload.skill_gap_id)
        if gap:
            skill_name = gap.skill_name
            gap_reason = gap.reason
            existing = cached_lesson(db, gap.id)
            if existing:
                return LessonResponse(
                    id=existing.id,
                    skill_gap_id=existing.skill_gap_id,
                    skill_name=existing.skill_name or skill_name,
                    theory_markdown=existing.theory_markdown,
                    starter_code=existing.starter_code,
                    solution_code=existing.solution_code,
                )

    # Generate lesson via agent
    generated = generate_lesson_agent(skill=skill_name, gap_reason=gap_reason)

    # Persist if skill_gap_id is provided
    lesson_id = None
    if payload.skill_gap_id:
        persisted = persist_lesson(
            db=db,
            skill_gap_id=payload.skill_gap_id,
            payload=generated,
            skill_name=skill_name,
        )
        lesson_id = persisted.id

    return LessonResponse(
        id=lesson_id,
        skill_gap_id=payload.skill_gap_id,
        skill_name=skill_name,
        theory_markdown=generated["theory_markdown"],
        starter_code=generated["starter_code"],
        solution_code=generated["solution_code"],
    )


@router.get("/lessons/{lesson_id}/attempts", response_model=list[AttemptHistoryItem])
def get_lesson_attempts(lesson_id: int, db: Session = Depends(get_db)):
    """Retrieve all recorded practice attempts for a given lesson."""
    attempts = get_attempts_for_lesson(db=db, lesson_id=lesson_id)
    return [
        AttemptHistoryItem(
            id=a.id,
            lesson_id=a.lesson_id,
            passed=a.passed,
            score=a.score,
            hint=a.hint,
            rubric={
                "correctness": a.correctness,
                "code_quality": a.code_quality,
                "concept_match": a.concept_match,
            },
            created_at=a.created_at.isoformat() if a.created_at else None,
        )
        for a in attempts
    ]
